services:
  mysql_db:
    image: mysql:8.4
    container_name: mysql-db-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
    